### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by EvanZune** [tomasonjo/trinity-ie#1]
Hi, I'm trying to run the jupyter notebook in your blog, and got this error.

"Failed to establish connection to IPv6Address"

Would you help?

**Comment by tomasonjo** [comment]
At which step does this error occur? It's weird as I don't know where the script would try to connect to IPv6 address.

**Comment by EvanZune** [comment]
driver = GraphDatabase.driver('bolt://localhost:7687', auth=('neo4j', 'letmein'))
I tried other port like 8080, and sometimes it results to IPv4 address. It's weird, it is necessary to run a docker on this specified port?

**Comment by tomasonjo** [comment]
This line connects to Neo4j. Do you have a Neo4j instance running on localhost?

**Comment by EvanZune** [comment]
> This line connects to Neo4j. Do you have a Neo4j instance running on localhost?

OK, I'll try
